name: Build and Release

on:
  pull_request:
    branches:
      - test
    types:
      - closed

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Create short commit SHA
      id: create_short_sha
      run: echo "::set-output name=sha_short::$(cd $GITHUB_WORKSPACE || git rev-parse --short ${{ github.event.pull_request.head.sha }})"
      
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        release_name: ${{ github.event.pull_request.title }} #pull request title
        body: ${{ github.event.pull_request.body }}
        tag_name: ${{ steps.create_short_sha.outputs.sha_short }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    

  build-android:
    name: Build android and upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk
        
      - name: Upload apk to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.jobs.create-release.outputs.upload_url }}
          asset_path: ${{ env.GITHUB_WORKSPACE }}/build/app/outputs/flutter-apk/app-release.apk
          asset_name: corecoder_develop_${{ needs.jobs.create-release.outputs.sha_short }}.apk
          asset_content_type: application/gzip
  build-windows:
    name: Build windows and upload
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Enable windows
        run: flutter config --enable-windows-desktop
      - name: Build windows
        run: flutter build windows
        #TODO: upload windows i dont know windows file path help
