name: Build and Release

on:
  pull_request:
    branches:
      - test
    types:
      - closed

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Create short commit SHA
      id: create_short_sha
      run: echo "::set-output name=sha_short::$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-8))"
      
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        release_name: ${{ github.event.pull_request.title }} #pull request title
        body: ${{ github.event.pull_request.body }}
        tag_name: ${{ steps.create_short_sha.outputs.sha_short }}
      env:
        GITHUB_TOKEN: ${{ github.token }}


    - id: step_upload_url
      run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}

  build-android:
    name: Build android and upload
    runs-on: ubuntu-latest
    needs: create-release 

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk
        
      - name: Upload apk to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
          asset_name: corecoder_develop_${{ needs.jobs.create-release.outputs.sha_short }}.apk
          asset_content_type: application/gzip
  build-windows:
    name: Build windows and upload
    runs-on: windows-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Enable windows
        run: flutter config --enable-windows-desktop
      - name: Build windows
        run: flutter build windows
      - name: Zip windows build
        run: zip -r corecoder_develop_${{ needs.jobs.create-release.outputs.sha_short }}.zip ${{ github.workspace }}/build/windows/runner/Release/
      - name: Upload windows build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/windows/runner/Release/corecoder_develop_${{ needs.jobs.create-release.outputs.sha_short }}.zip
          asset_name: corecoder_develop_${{ needs.jobs.create-release.outputs.sha_short }}.zip
          asset_content_type: application/gzip
