name: Build on Push

on:
  push:

jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk
        
      - name: Build appbundle
        run: flutter build appbundle
  build-windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Install dependencies
        run: flutter pub get
      - name: Enable windows
        run: flutter config --enable-windows-desktop
      - name: Build windows
        run: flutter build windows
